### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by huitc** [m4ll0k/Atlas#11]
```
python2 atlas.py -v -r -m GET -u "http://event.test.com.us/index.php/event/start/3" -p "3'"
```
```
[*] Starting at 05:32:27

[05:32:27] [INFO] testing connection to the target URL...
[05:32:27] [INFO] checking if the payload is blocked by some kind of WAF/IDS/IPS..
Traceback (most recent call last):
  File "atlas.py", line 265, in <module>
    atlas().main()
  File "atlas.py", line 201, in main
    url,method,data,kwargs
  File "atlas.py", line 32, in run
    for url in testable.run():
  File "/data/data/com.termux/files/home/atlas/lib/params.py", line 29, in run
    elif '=' not in self.url and '=' in self.data:self.post()
TypeError: argument of type 'NoneType' is not iterable
$
```

**Comment by huitc** [comment]
`%inject here%`?

**Comment by ekonaren** [comment]
Any update on this issue?

**Comment by codecrimson** [comment]
This tool only works if you have query parameters (?foo=bar). If the parameter is part of the URI, it won't be able to parse it.

e.g. http://event.test.com.us/index.php/event?start=3 would work, but http://event.test.com.us/index.php/event/start/3 will not.
