### ISSUE TITLE
If the WAF is resetting connection, the tool is basically useless

### ISSUE THREAD

**Issue by thistehneisen** [m4ll0k/Atlas#13]
```
Traceback (most recent call last):
  File "atlas.py", line 337, in <module>
    atlas().main()
  File "atlas.py", line 238, in main
    code = get_code.run()
  File "atlas.py", line 41, in run
    resp = self.send(url,self.method,self.data,injected.get('headers'))
  File "/Users/NULL/Code/Python/Atlas/lib/request.py", line 63, in send
    resp = urllib2.urlopen(req)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by m4ll0k** [comment]
Hi @thistehneisen - https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean

**Comment by thistehneisen** [comment]
I mean that's understood, but in this case the "WAF" is probably .htaccess ruleset, which prevents specific keywords being in the address. I think Atlas could try to pivot around them also. Just a thought.
