### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Shahad7278** [m4ll0k/Atlas#22]
python3 atlas.py 
Traceback (most recent call last):
  File "atlas.py", line 16, in <module>
    from humanfriendly.tables import format_pretty_table as pretty
ModuleNotFoundError: No module named 'humanfriendly'

**Comment by Shahad7278** [comment]
root@kali:~/tools/atlas# python atlas.py --url http://site.com/index.php?id=Price_ASC --payload="-1234 AND 4321=4321-- AAAA"
  File "atlas.py", line 20
    def __init__(self,url:str,method:str,data:str,kwargs:dict)->None:
                         ^
SyntaxError: invalid syntax

**Comment by mplengsangrai** [comment]
> python3 atlas.py Traceback (most recent call last): File "atlas.py", line 16, in from humanfriendly.tables import format_pretty_table as pretty ModuleNotFoundError: No module named 'humanfriendly'

python3 -m pip install humanfriendly
